import React from "react";
import { Box, Heading, Text, Image } from "@chakra-ui/react";
const Poster = require("../images/1576775063227.jpeg");
const FootPrints = require("../images/carbon-footprint.jpg");
const WhyEcosavvy = require("../images/eco.jpg");

const HomePage = () => {
  return (
    <>
      <Box
        px={{ base: 4, md: 20 }}
        py={{ base: 6, md: 10 }}
        fontSize="large"
        backgroundColor="green.700"
        color="white"
      >
        {/* Welcome Section */}
        <Box textAlign="center" mb={8}>
          <Heading as="h1" mb={2}>
            Welcome to CarbonEliminator
          </Heading>
          <Text fontSize="lg">Your Guide to Sustainable Living</Text>
        </Box>

        <Image
          src={Poster}
          alt="Landscape"
          maxW="100%"
          mb={8}
          height={{ base: 300, md: 500 }}
          width={{ base: "100%", md: 900 }}
          mx="auto"
          borderRadius={5}
        />

        <Text mb={15}>
          Carbon emission control is crucial for mitigating climate change and achieving sustainable development. Carbon emissions from fossil fuels and deforestation cause global warming, leading to severe environmental and socio-economic impacts. Effective strategies, including policies, clean technologies, and sustainable practices, are essential for reducing emissions. Collaborative efforts between governments, industries, and communities are vital to implement these strategies. Additionally, raising public awareness and promoting behavioral changes can significantly contribute to reducing the global carbon footprint. Investing in renewable energy sources and enhancing energy efficiency are also key components in the fight against climate change.
        </Text>
        <br />

        <Box mb={8} display={{ md: "flex" }} gap="10">
          <Box flex={{ base: 1, md: 1 }} mb={{ base: 6, md: 0 }}>
            <Heading as="h2" size="lg" mb={5} textAlign="center">
              What Is Your Carbon Footprint? Learn How to Reduce It.
            </Heading>
            <Text>
              A carbon footprint is the total amount of greenhouse gases (including CO2 and methane) generated by our actions. The average carbon footprint in the U.S. is 16 tons per person, compared to a global average of 4 tons.
              <br />
              To avoid a catastrophic 2℃ rise in global temperatures, this needs to drop below 2 tons by 2050.
              <br />
              Reducing individual footprints from 16 to 2 tons requires gradual changes. Simple actions like eating less meat, taking fewer flights, and line drying clothes can make a big difference. Using energy-efficient appliances, reducing waste, recycling, and opting for public transportation or carpooling also help.
              <br />
              These actions align with the United Nations Sustainable Development Goals (SDGs), particularly:
              <br />
              Goal 7: Affordable and Clean Energy
              <br />
              Goal 11: Sustainable Cities and Communities
              <br />
              Goal 12: Responsible Consumption and Production
              <br />
              Goal 13: Climate Action
              <br />
              By collectively making these changes, we contribute to a larger movement towards a sustainable future, helping to protect our planet for generations to come and ensuring we meet the targets set by the SDGs.
            </Text>
          </Box>
          <Box flex={{ base: 1, md: 1 }}>
            <Image
              src={FootPrints}
              alt="What is Ecosavvy Image"
              maxW="100%"
              borderRadius={5}
            />
          </Box>
        </Box>
        <br />

        <Box mb={8} display={{ md: "flex" }} gap="10">
          <Box flex={{ base: 1, md: 1 }} order={{ base: 2, md: 1 }} mb={{ base: 6, md: 0 }}>
            <Image
              src={WhyEcosavvy}
              alt="Why Choose Ecosavvy Image"
              maxW="100%"
              borderRadius={10}
            />
          </Box>
          <Box flex={{ base: 1, md: 1 }} order={{ base: 1, md: 2 }} ml={{ md: 4 }}>
            <Heading as="h2" size="lg" mb={2} textAlign="center">
              Concept of CarbonEliminator
            </Heading>
            <Text>
              The Concept of CarbonEliminator is to design and implement strategies to control carbon emissions, thereby contributing to the achievement of Sustainable Development Goals (SDGs). The focus will be on integrating technological, policy, and behavioral approaches to reduce carbon footprints and promote sustainable development. By leveraging cutting-edge technologies, advocating for effective policies, and encouraging behavioral changes, CarbonEliminator seeks to provide a comprehensive solution for a more sustainable and eco-friendly future.
            </Text>
          </Box>
        </Box>
      </Box>
      <Box
        backgroundColor="white"
        color="green.700"
        py={4}
        textAlign="center"
        fontWeight="bold"
      >
        © 2024 IBM Sustainable Development Goals (SDGs).
      </Box>
    </>
  );
};

export default HomePage;
